insert into store_promotion (id, description, discount) values (1, 'Nam congue, risus semper porta  quis orci.', 26.7253);
insert into store_promotion (id, description, discount) values (2, 'Maecenas pulvinar lobortis est.', 22.7033);
insert into store_promotion (id, description, discount) values (3, 'Nam dui.', 21.0221);
insert into store_promotion (id, description, discount) values (4, 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 28.6663);
insert into store_promotion (id, description, discount) values (5, 'Maecenas pulvinar lobortis est.', 23.7645);
insert into store_promotion (id, description, discount) values (6, 'Integer a nibh.', 29.3406);
insert into store_promotion (id, description, discount) values (7, 'Fusce consequat.', 12.2139);
insert into store_promotion (id, description, discount) values (8, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', 2.1266);
insert into store_promotion (id, description, discount) values (9, 'Morbi non quam nec dui luctus rutrum.', 22.5706);
insert into store_promotion (id, description, discount) values (10, 'Maecenas rhoncus aliquam lacus.', 16.6702);
insert into store_promotion (id, description, discount) values (11, 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 2.1586);
insert into store_promotion (id, description, discount) values (12, 'Morbi non quam nec dui luctus rutrum.', 25.5684);
insert into store_promotion (id, description, discount) values (13, 'Vestibulum ante ipsum primis Donec pharetr.', 27.5013);
insert into store_promotion (id, description, discount) values (14, 'Morbi non lectus.', 17.4096);
insert into store_promotion (id, description, discount) values (15, 'Proin eu mi.', 14.0665);
insert into store_promotion (id, description, discount) values (16, 'Nulla nisl.', 24.2726);
insert into store_promotion (id, description, discount) values (17, 'Integer pedetempus vel, pede.', 8.6536);
insert into store_promotion (id, description, discount) values (18, 'In hac habitasse platea dictumst.', 17.5673);
insert into store_promotion (id, description, discount) values (19, 'Suspendisse potenti.', 2.116);
insert into store_promotion (id, description, discount) values (20, 'Etiam vel augue.', 27.4914);
insert into store_promotion (id, description, discount) values (21, 'Fusce consequat.', 19.5222);
insert into store_promotion (id, description, discount) values (22, 'Maecenas tincidunt lacus at velit.', 29.9123);
insert into store_promotion (id, description, discount) values (23, 'Cum sociis natoque penaiculus mus.', 16.2045);
insert into store_promotion (id, description, discount) values (24, 'Mauris enim leo, rhoncus sed,us id, turpis.', 3.8972);
insert into store_promotion (id, description, discount) values (25, 'Etiam faucibus cursus urna.', 5.5288);
