insert into store_collection (id, title) values (1, 'Broom And Brush Rack Black');
insert into store_collection (id, title) values (2, 'Onion Powder');
insert into store_collection (id, title) values (3, 'Flavouring - Rum');
insert into store_collection (id, title) values (4, 'Pear - Packum');
insert into store_collection (id, title) values (5, 'Pasta - Tortellini, Fresh');
insert into store_collection (id, title) values (6, 'Orange - Blood');
insert into store_collection (id, title) values (7, 'Eel Fresh');
insert into store_collection (id, title) values (8, 'Beef Dry Aged Tenderloin Aaa');
insert into store_collection (id, title) values (9, 'Plastic Wrap');
insert into store_collection (id, title) values (10, 'Onions - Red Pearl');
insert into store_collection (id, title) values (11, 'Artichoke - Fresh');
insert into store_collection (id, title) values (12, 'Fennel');
insert into store_collection (id, title) values (13, 'Chicken - Leg / Back Attach');
insert into store_collection (id, title) values (14, 'Beer - Blue Light');
insert into store_collection (id, title) values (15, 'Mayonnaise');
insert into store_collection (id, title) values (16, 'Lettuce - Baby Salad Greens');
insert into store_collection (id, title) values (17, 'Flour - Bread');
insert into store_collection (id, title) values (18, 'Wine - Riesling Dr. Pauly');
insert into store_collection (id, title) values (19, 'Pork - Chop, Frenched');
insert into store_collection (id, title) values (20, 'Flour - Strong Pizza');
insert into store_collection (id, title) values (21, 'Soup - Campbells Pasta Fagioli');
insert into store_collection (id, title) values (22, 'Cod - Salted, Boneless');
insert into store_collection (id, title) values (23, 'Beef - Striploin Aa');
insert into store_collection (id, title) values (24, 'Cheese - Cheddar, Old White');
insert into store_collection (id, title) values (25, 'Bag - Bread, White, Plain');
