insert into store_promotion (id, description, discount, feature_product_id) values (1, 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', 26.7253, '1');
insert into store_promotion (id, description, discount, feature_product_id) values (2, 'Maecenas pulvinar lobortis est.', 22.7033, '2');
insert into store_promotion (id, description, discount, feature_product_id) values (3, 'Nam dui.', 21.0221, '5');
insert into store_promotion (id, description, discount, feature_product_id) values (4, 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 28.6663, '8');
insert into store_promotion (id, description, discount, feature_product_id) values (5, 'Maecenas pulvinar lobortis est.', 23.7645, '7');
insert into store_promotion (id, description, discount, feature_product_id) values (6, 'Integer a nibh.', 29.3406, '8');
insert into store_promotion (id, description, discount, feature_product_id) values (7, 'Fusce consequat.', 12.2139, '7');
insert into store_promotion (id, description, discount, feature_product_id) values (8, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', 2.1266, '8');
insert into store_promotion (id, description, discount, feature_product_id) values (9, 'Morbi non quam nec dui luctus rutrum.', 22.5706, '6');
insert into store_promotion (id, description, discount, feature_product_id) values (10, 'Maecenas rhoncus aliquam lacus.', 16.6702, '9');
insert into store_promotion (id, description, discount, feature_product_id) values (11, 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 2.1586, '7');
insert into store_promotion (id, description, discount, feature_product_id) values (12, 'Morbi non quam nec dui luctus rutrum.', 25.5684, '7');
insert into store_promotion (id, description, discount, feature_product_id) values (13, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.', 27.5013, '4');
insert into store_promotion (id, description, discount, feature_product_id) values (14, 'Morbi non lectus.', 17.4096, '6');
insert into store_promotion (id, description, discount, feature_product_id) values (15, 'Proin eu mi.', 14.0665, '1');
insert into store_promotion (id, description, discount, feature_product_id) values (16, 'Nulla nisl.', 24.2726, '5');
insert into store_promotion (id, description, discount, feature_product_id) values (17, 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 8.6536, '2');
insert into store_promotion (id, description, discount, feature_product_id) values (18, 'In hac habitasse platea dictumst.', 17.5673, '2');
insert into store_promotion (id, description, discount, feature_product_id) values (19, 'Suspendisse potenti.', 2.116, '2');
insert into store_promotion (id, description, discount, feature_product_id) values (20, 'Etiam vel augue.', 27.4914, '4');
insert into store_promotion (id, description, discount, feature_product_id) values (21, 'Fusce consequat.', 19.5222, '4');
insert into store_promotion (id, description, discount, feature_product_id) values (22, 'Maecenas tincidunt lacus at velit.', 29.9123, '7');
insert into store_promotion (id, description, discount, feature_product_id) values (23, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 16.2045, '5');
insert into store_promotion (id, description, discount, feature_product_id) values (24, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 3.8972, '2');
insert into store_promotion (id, description, discount, feature_product_id) values (25, 'Etiam faucibus cursus urna.', 5.5288, '2');
