insert into tags_tag (id, label) values (1, 'Lucky You');
insert into tags_tag (id, label) values (2, 'Stephen Fry In America - New World');
insert into tags_tag (id, label) values (3, 'Redline');
insert into tags_tag (id, label) values (4, 'Stuff, The');
insert into tags_tag (id, label) values (5, 'Big Country, The');
insert into tags_tag (id, label) values (6, 'Early Spring (Soshun)');
insert into tags_tag (id, label) values (7, 'Carriage to Vienna');
insert into tags_tag (id, label) values (8, 'The Things of Life');
insert into tags_tag (id, label) values (9, 'Birders: The Central Park Effect (Central Park Effect, The)');
insert into tags_tag (id, label) values (10, 'Monkey in Winter, A (Un singe en hiver)');
insert into tags_tag (id, label) values (11, 'Pretty Woman');
insert into tags_tag (id, label) values (12, 'End of the Spear');
insert into tags_tag (id, label) values (13, 'Solomon Northup''s Odyssey');
insert into tags_tag (id, label) values (14, 'Little Nikita');
insert into tags_tag (id, label) values (15, 'I Am (Jestem)');
insert into tags_tag (id, label) values (16, 'Roman de gare');
insert into tags_tag (id, label) values (17, 'Schultze Gets the Blues');
insert into tags_tag (id, label) values (18, 'Signs');
insert into tags_tag (id, label) values (19, 'Left Behind');
insert into tags_tag (id, label) values (20, 'Sneakers');
insert into tags_tag (id, label) values (21, 'Fort McCoy');
insert into tags_tag (id, label) values (22, 'Pavement: Slow Century');
insert into tags_tag (id, label) values (23, 'April Captains (Capitães de Abril)');
insert into tags_tag (id, label) values (24, 'Mr. Kinky');
insert into tags_tag (id, label) values (25, 'Eight Crazy Nights (Adam Sandler''s Eight Crazy Nights)');
