# Generated by Django 5.0.1 on 2024-01-24 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("""
                    INSERT INTO store_collection(title)
                    VALUES('collection1')
                          """,
                    """ 
                    DELETE store_collection
                    where title = 'collection1'
""")
    ]
