# Generated by Django 5.0.1 on 2024-01-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='points',
            field=models.IntegerField(default=50),
        ),
    ]
