# Generated by Django 5.0.4 on 2024-04-24 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_customer_options_remove_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['id'], 'permissions': [('cancel_order', 'Can cancel order')]},
        ),
    ]
